# NUMPY in PYTHON

#### Numpy is the short form of Numerical Python. Core library for scientific computing. 

In [3]:
#Importing numpy for computing

import numpy as np


In [5]:
#Creation of Numpy array from list, arange

vector_size = 1000 #assigning a variable

X = np.arange(vector_size) #creation of np array using arange()

Z = list(range(150)) #creation of list using range()

Y = np.array(Z) #creation of np array from list.

In [6]:
print(type(Z))

print(type(X))

print(type(Y))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Attributes of N-dimensional Array


ndarray.shape -> Tuple of array dimensions.

ndarray.strides -> Tuple of bytes to step in each dimension when traversing an array.

ndarray.ndim -> Number of array dimensions.

ndarray.size -> Number of elements in the array.

ndarray.itemsize -> Length of one array element in bytes.

ndarray.nbytes -> Total bytes consumed by the elements of the array.

In [7]:
#ndim -> to find out which dimension it is

X.ndim

1

In [9]:
A = np.arange(24).reshape(6,4)
print(A)
A.ndim

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


2

In [10]:
B = np.arange(24).reshape(3,4,2)
print(B)
B.ndim

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


3

In [11]:
C = np.arange(24).reshape(2,2,3,2)
print(C)
C.ndim

[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]


4

In [12]:
#Shape provides a tuple output (no of rows, no of columns)

C.shape

(2, 2, 3, 2)

In [13]:
X.shape

(1000,)

In [14]:
Y.shape

(150,)

In [15]:
A.shape

(6, 4)

In [16]:
X.size

1000

In [17]:
C.size

24

In [18]:
C.itemsize

4

In [19]:
X.itemsize

4

In [21]:
C.nbytes

96

In [22]:
C.strides

(48, 24, 8, 4)

In [23]:
A.reshape(2,3,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Functions in Numpy Array

In [24]:
z1 = np.zeros
print(z1)

<built-in function zeros>


In [27]:
#np.zeros(shape = (rows, columns), dtype = "int32") -> creates an array with all elements as zeroes.

z2 = np.zeros(shape = (3,3),dtype = "int32")
print(z2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
#np.ones(shape = (rows, columns), dtype = "int32") -> creates an array with all elements as ones.

z3 = np.ones(shape = (2,2), dtype = "int32")
print(z3)

[[1 1]
 [1 1]]


In [29]:
#np.arange(start,stop, increment) -> start(inclusive), stop(exclusive), increment(stepsize)

r = np.arange(0,1,0.1)
print(r)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [31]:
#np.empty(shape = (r,c)) -> creates an array with initial random content and it depends on the state of the memory.

e = np.empty(shape = (2,2))
print(e)

[[8.77394705e-312 2.21654027e-301]
 [1.65095003e-287 3.21401734e-308]]


In [35]:
#np.full(shape = (r,c),fill_value) -> creates an array with same rows and columns with the mentioned value

f = np.full((3,4),5)
print(f)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [37]:
#np.eye(shape = (r,c)) -> creates an array with diagonal elements as 1 and the remaining elements as 0 with float data type elements.
g = np.eye(2,3)
print(g)
g.dtype

[[1. 0. 0.]
 [0. 1. 0.]]


dtype('float64')

In [38]:
#np.linspace(starting num, stopping num, no of partitions) -> starting num and stopping num also included in the array

h = np.linspace(2,10,10)
print(h)

[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


In [45]:
#np.random.random((r,c)) -> create an array with random values from 0 to 1 

i = np.random.random((2,3))
print(i)

[[0.09705762 0.27611863 0.92917845]
 [0.37542449 0.80487725 0.5954743 ]]


In [46]:
#np.flatten() -> converts multi dimensional array to an one dimensional array with the same elements.

C = np.arange(24).reshape(2,2,3,2)
print(C)
C.ndim
j = C.flatten()
print(j)
j.ndim

[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


1

In [47]:
#np.ravel() -> returns a flattened view of an array collapsed into one dimension. Ti works similar to flatten(). But, a copy in memory is not achieve

k = C.ravel()
print(k)
k.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


1

Some key differences between flattening and raveling the array are:

ravel() function simply returns a flattened view of Numpy array. If you try to modify this view, you will end up with that same changes in the original array. flatten() function returns a flattened copy in memory of the array, so that new changes can be made without affecting the original array.

ravel() does not occupy memory, being faster than flatten(), which occupies memory when copying the flattened objects.

### Array Indexing

Single Positive Indexing

Single Negative Indexing

Positive Index Intervals

Negative Index Intervals

In [4]:
array_np = np.arange(5)
print(array_np)

#To a particular element from the array which is 1 dimensional.
array_np[2]

[0 1 2 3 4]


2

In [6]:
#To access 2 dimensional array 
A = np.arange(24).reshape(6,4)
print(A)

A[2][2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


10

In [7]:
#Accessing elements using Negative indexing

A[-5]

array([4, 5, 6, 7])

In [8]:
#Accessing elements using Negative Indexing 

A[-1][-4]

20

In [9]:
#Accessing elements using postive intervals indexing

A[2:5]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
A[5:]

array([[20, 21, 22, 23]])

In [17]:
A[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
A[:2, ::3]

array([[0, 3],
       [4, 7]])

In [16]:
A[:2, :2]

array([[0, 1],
       [4, 5]])

In [20]:
A[:2, 2:]

array([[2, 3],
       [6, 7]])

In [22]:
A[:2, 1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [28]:
print(A)
A[:-2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
A[:-2, :-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [30]:
#Accessing the the intervals from -2

A[:-2, ::-2]

array([[ 3,  1],
       [ 7,  5],
       [11,  9],
       [15, 13]])

In [31]:
np1 = np.array([1, 8, 3, 7, 3, 21])
np2 = np.array([4, 8, 1, 7, 6, 9])

sum1 = np1 + np2
sub1 = np1 - np2
mul1 = np1 * np2
div1 = np1 / np2

print(sum1)
print(sub1)
print(mul1)
print(div1)

[ 5 16  4 14  9 30]
[-3  0  2  0 -3 12]
[  4  64   3  49  18 189]
[0.25       1.         3.         1.         0.5        2.33333333]


In [32]:
#If both the elements in the np array are same then it will be True otherwise it will be False

np.equal(np1,np2)

array([False,  True, False,  True, False, False])

In [33]:
np.not_equal(np1,np2)

array([ True, False,  True, False,  True,  True])

In [35]:
#Broadcasting -> ability of NumPy to treat arrays of different shapes during arithmetic operations. 

np_a1 = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
np_b1 = np.array([1.0,2.0,3.0])  
   
print('First array:')
print(np_a1)
print('\n')
   
print('Second array:')
print(np_b1) 
print('\n')
   
print('First Array + Second Array')
print(np_a1 + np_b1)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


A random number is a result of a variable combination specified by a distribution function. When no distribution is specified, it is assumed that the continuous uniform distribution in the interval [0,1) is used. Some functions for generating random numpy numbers are:

np.random.random(): returns random floats in the half-open interval [0.0, 1.0)

np.random.randint(low, high): returns random integers from low (inclusive) to high (exclusive).

np.random.normal(): returns random samples from a normal (Gaussian) distribution.

In [36]:
np.random.randint(10, 20, size=(2, 4))

array([[12, 11, 14, 12],
       [16, 10, 13, 14]])

In [37]:
np.random.normal(size=10)

array([ 1.50642764,  0.82696268,  0.01874627, -0.37711066, -0.15446399,
       -1.36356635,  0.01205456, -0.24500003,  0.25696848,  0.52803258])